---
- hosts: app
  become: true
  tasks:
    - name: install git 
      yum:
        name: git
        state: latest

    - name: clone studentlist repo 
      git:
        repo: http://192.168.31.148/root/studentList
        dest: /root/studentList
        version: master

    # - name: Create and start services
    #   docker_compose:
    #     project_src: /root/studentList
    #   register: output

    # - debug:
    #     var: output
    

    - name:  start docker-compose 
      become: True
      shell:
        cmd: "docker-compose up "
        chdir: /root/studentList/


    # - name: Deploy 4dvop-haproxy
    #   docker_container:
    #     name: haproxy
    #     hostname: haproxy
    #     image: celsosanchez/haproxy-4dvop
    #     state: started
    #     links:
    #       - nginx:nginx
    #     ports:
    #       - "80:80"
