---
- hosts: app
  become: true
  tasks:
    - name: install git 
      yum:
        name: git
        state: latest

    - name: clone studentlist repo 
      git:
        repo: http://192.168.31.148/root/studentList.git
        dest: /root/studentList
        version: master

    # - name:  ensure insecure registry 
    #   become: True
    #   shell:
    #     cmd: 'printf "{\n  \"insecure-registries\" : [\"192.168.31.21:5000\"] \n}\n"| cat>/etc/docker/daemon.json'
    #     chdir: /root/studentList/
 
    # - name:  reload docker config 
    #   become: True
    #   shell:
    #     cmd: 'systemctl daemon-reload'
  
    # - name:  restart docker 
    #   become: True
    #   shell:
    #     cmd: 'systemctl restart docker'
 
    - name:  start docker-compose 
      become: True
      shell:
        cmd: "docker-compose up -d "
        chdir: /root/studentList/

