---
- hosts: app
  become: true
  tasks:
    - name: clone studentlist repo 
      git:
        repo: http://192.168.31.148/root/studentList
        dest: /root/studentList
        version: master

          
    # - name: Deploy 4dvop-haproxy
    #   docker_container:
    #     name: haproxy
    #     hostname: haproxy
    #     image: celsosanchez/haproxy-4dvop
    #     state: started
    #     links:
    #       - nginx:nginx
    #     ports:
    #       - "80:80"
