---
- hosts: app
  become: true
  tasks:
    - name: install git 
      yum:
        name: git
        state: latest

    - name: clone studentlist repo 
      git:
        repo: http://192.168.31.148/root/studentList.git
        dest: /root/studentList
        version: master

 

    - name:  ensure insecure registry 
      become: True
      shell:
        cmd: 'printf "{\n  "insecure-registries" : ["192.168.31.21:5000"] \n}"| cat>/etc/docker/daemon.json'
        chdir: /root/studentList/
 
    - name:  start docker-compose 
      become: True
      shell:
        cmd: "docker-compose up "
        chdir: /root/studentList/


    # - name: Deploy 4dvop-haproxy
    #   docker_container:
    #     name: haproxy
    #     hostname: haproxy
    #     image: celsosanchez/haproxy-4dvop
    #     state: started
    #     links:
    #       - nginx:nginx
    #     ports:
    #       - "80:80"
